# frozen_string_literal: true

require "minitest/autorun"
require "open3"
require "pathname"
require "yaml"

class LegacyLearningEntryTest < Minitest::Test
  ROOT = Pathname(__dir__).join("../..").expand_path
  MAPPING = ROOT.join("curriculum/compatibility/legacy-weeks.yml")
  MARKER = "generated by scripts/sync-legacy-learning-entry.rb"

  def test_mapping_is_complete_and_only_references_canonical_chapters
    mapping = YAML.safe_load(MAPPING.read, aliases: false)
    catalog = YAML.safe_load(ROOT.join("curriculum/catalog.yml").read, aliases: false)
    ids = catalog.fetch("chapters").map { |chapter| chapter.fetch("id") }
    weeks = mapping.fetch("weeks")

    assert_equal((0..48).to_a, weeks.map { |week| week.fetch("week") })
    assert_equal 49, weeks.length
    weeks.each do |week|
      refute_empty week.fetch("chapter_ids"), "week #{week.fetch('week')}"
      assert_empty week.fetch("chapter_ids") - ids, "week #{week.fetch('week')}"
    end
  end

  def test_generated_adapters_are_current_and_links_resolve
    output, error, status = Open3.capture3(
      "ruby", "scripts/sync-legacy-learning-entry.rb", "--check", chdir: ROOT.to_s
    )
    assert status.success?, "#{output}\n#{error}"

    pages = [ROOT.join("weeks/README.md")]
    pages.concat((0..48).map { |week| ROOT.join(format("weeks/week-%02d.md", week)) })
    pages.concat((0..8).map { |week| ROOT.join(format("learning-kits/week-%02d/concepts.md", week)) })
    pages.each do |page|
      body = page.read
      assert_includes body, MARKER, page.to_s
      refute_includes body, "## 完整概念清单", page.to_s
      body.scan(/\[[^\]]+\]\(([^)]+)\)/).flatten.each do |target|
        next if target.match?(/\A(?:https?:|#)/)

        resolved = page.dirname.join(target.split("#", 2).first).cleanpath
        assert resolved.exist?, "broken link #{target} in #{page.relative_path_from(ROOT)}"
      end
    end
  end

  def test_frozen_rollback_tag_exists
    _output, error, status = Open3.capture3(
      "git", "rev-parse", "--verify", "refs/tags/pre-encyclopedia-2026-07-16^{commit}", chdir: ROOT.to_s
    )
    assert status.success?, error
  end
end
