# frozen_string_literal: true

require "fileutils"
require "json"
require "minitest/autorun"
require "open3"
require "pathname"
require "tmpdir"
require "yaml"

require_relative "../../scripts/lib/legacy_week_compiler"

class LegacyLearningEntryTest < Minitest::Test
  ROOT = Pathname(__dir__).join("../..").expand_path
  MAPPING = ROOT.join("curriculum/compatibility/legacy-weeks.yml")
  MARKER = "generated by scripts/sync-legacy-learning-entry.rb"
  SECTIONS = %w[required practice_diagnosis review support].freeze

  def setup
    @mapping = YAML.safe_load(MAPPING.read, aliases: false)
    @catalog = YAML.safe_load(ROOT.join("curriculum/catalog.yml").read, aliases: false)
  end

  def test_mapping_has_49_bounded_weeks_and_exact_primary_outcome_coverage
    weeks = @mapping.fetch("weeks")
    assert_equal 2, @mapping.fetch("schema_version")
    assert_equal "outcome-slice-adapter", @mapping.fetch("policy")
    assert_equal((0..48).to_a, weeks.map { |week| week.fetch("week") })
    assert_equal 49, weeks.length

    expected = @catalog.fetch("chapters").flat_map do |chapter|
      chapter.fetch("outcomes").map { |outcome| "#{chapter.fetch('id')}##{outcome.fetch('id')}" }
    end
    primary = weeks.flat_map { |week| week.fetch("required") + week.fetch("practice_diagnosis") }
    assert_equal 255, primary.map { |ref| ref.split("#", 2).first }.uniq.length
    assert_equal 765, primary.length
    assert_equal expected.sort, primary.sort
    assert_equal primary.length, primary.uniq.length

    weeks.each do |week|
      budget = week.fetch("budget_hours")
      expected_range = week.fetch("week").zero? ? [8, 12] : [15, 18]
      assert_equal expected_range, [budget.fetch("minimum"), budget.fetch("maximum")]
      assert_operator budget.fetch("target"), :>=, budget.fetch("minimum")
      assert_operator budget.fetch("target"), :<=, budget.fetch("maximum")
      assert_equal budget.fetch("target"), budget.fetch("allocation").values.sum
      assert_equal SECTIONS, budget.fetch("allocation").keys
    end
  end

  def test_progress_themes_are_preserved_without_changing_progress
    progress_themes = {}
    ROOT.join("PROGRESS.md").each_line do |line|
      match = line.match(/^\|\s*(\d{2})\s*\|\s*([^|]+?)\s*\|/)
      progress_themes[match[1].to_i] = match[2].strip if match
    end

    assert_equal((0..48).to_a, progress_themes.keys.sort)
    assert_equal progress_themes, @mapping.fetch("weeks").to_h { |week| [week.fetch("week"), week.fetch("progress_theme")] }
  end

  def test_reference_depth_and_route_mastery_are_independent
    weeks = @mapping.fetch("weeks")
    assert_equal "L1-L2", weeks.fetch(39).fetch("required_mastery")
    (40..43).each { |number| assert_equal "L2+", weeks.fetch(number).fetch("required_mastery") }

    levels = @catalog.fetch("chapters").to_h { |chapter| [chapter.fetch("id"), chapter.fetch("level")] }
    ml_refs = weeks.fetch(39).fetch("required") + weeks.fetch(39).fetch("practice_diagnosis")
    ai_refs = (40..43).flat_map do |number|
      weeks.fetch(number).fetch("required") + weeks.fetch(number).fetch("practice_diagnosis")
    end
    assert ml_refs.any? { |ref| levels.fetch(ref.split("#", 2).first) == "L3" }, "ML route must retain L3 reference chapters while requiring L1-L2"
    assert ai_refs.any? { |ref| levels.fetch(ref.split("#", 2).first) == "L3" }, "AI route must retain L3 reference chapters while requiring L2+"

    profiles = @mapping.dig("mastery_policy", "profiles")
    weeks.each do |week|
      assert_equal profiles.fetch(week.fetch("required_mastery")), week.fetch("evidence_requirements")
    end
  end

  def test_generated_adapters_are_current_and_show_all_four_roles
    output, error, status = Open3.capture3(
      "ruby", "scripts/sync-legacy-learning-entry.rb", "--check", chdir: ROOT.to_s
    )
    assert status.success?, "#{output}\n#{error}"
    assert_includes output, "chapters=255"
    assert_includes output, "primary_outcomes=765"

    pages = [ROOT.join("weeks/README.md")]
    week_pages = (0..48).map { |week| ROOT.join(format("weeks/week-%02d.md", week)) }
    pages.concat(week_pages)
    pages.concat((0..8).map { |week| ROOT.join(format("learning-kits/week-%02d/concepts.md", week)) })
    pages.each do |page|
      body = page.read
      assert_includes body, MARKER, page.to_s
      body.scan(/\[[^\]]+\]\(([^)]+)\)/).flatten.each do |target|
        next if target.match?(/\A(?:https?:|#)/)

        resolved = page.dirname.join(target.split("#", 2).first).cleanpath
        assert resolved.exist?, "broken link #{target} in #{page.relative_path_from(ROOT)}"
      end
    end
    week_pages.each do |page|
      body = page.read
      assert_includes body, "## 必修解释（primary）"
      assert_includes body, "## 实践与诊断（primary）"
      assert_includes body, "## 间隔复习（refresh）"
      assert_includes body, "## 前置支撑（support）"
      assert_includes body, "## 本周投入与掌握边界"
    end
  end

  def test_missing_primary_outcome_fails_closed
    error = compile_mutation do |mapping|
      mapping.fetch("weeks").fetch(0).fetch("required").shift
    end
    assert_equal "E_PRIMARY_COVERAGE", error.code
    assert_includes error.message, "missing="
  end

  def test_duplicate_primary_owner_fails_closed
    error = compile_mutation do |mapping|
      ref = mapping.fetch("weeks").fetch(0).fetch("required").first
      mapping.fetch("weeks").fetch(1).fetch("required") << ref
    end
    assert_equal "E_PRIMARY_COVERAGE", error.code
    assert_includes error.message, "duplicates="
  end

  def test_missing_mastery_fails_schema_closed
    error = compile_mutation do |mapping|
      mapping.fetch("weeks").fetch(40).delete("required_mastery")
    end
    assert_equal "E_WEEK_SCHEMA", error.code
    assert_includes error.message, "required_mastery"
  end

  def test_mastery_evidence_mismatch_fails_closed
    error = compile_mutation do |mapping|
      mapping.fetch("weeks").fetch(40)["evidence_requirements"] = %w[timed-teach-back]
    end
    assert_equal "E_MASTERY_EVIDENCE", error.code
  end

  def test_future_refresh_and_invalid_budget_fail_closed
    future_error = compile_mutation do |mapping|
      mapping.fetch("weeks").fetch(1)["review"] = [mapping.fetch("weeks").fetch(2).fetch("required").first]
      mapping.fetch("weeks").fetch(1).fetch("budget_hours").fetch("allocation")["review"] = 2
    end
    assert_equal "E_REFRESH_ORDER", future_error.code

    budget_error = compile_mutation do |mapping|
      mapping.fetch("weeks").fetch(12).fetch("budget_hours")["maximum"] = 20
    end
    assert_equal "E_WEEK_BUDGET", budget_error.code
  end

  def test_frozen_rollback_tag_exists
    _output, error, status = Open3.capture3(
      "git", "rev-parse", "--verify", "refs/tags/pre-encyclopedia-2026-07-16^{commit}", chdir: ROOT.to_s
    )
    assert status.success?, error
  end

  private

  def compile_mutation
    Dir.mktmpdir("legacy-week-slices-") do |directory|
      root = Pathname(directory)
      %w[curriculum/compatibility schemas].each { |relative| root.join(relative).mkpath }
      FileUtils.cp(ROOT.join("curriculum/catalog.yml"), root.join("curriculum/catalog.yml"))
      FileUtils.cp(ROOT.join("schemas/legacy-week-slices.schema.json"), root.join("schemas/legacy-week-slices.schema.json"))
      FileUtils.cp(ROOT.join("PROGRESS.md"), root.join("PROGRESS.md"))

      mapping = JSON.parse(JSON.generate(@mapping))
      yield mapping
      root.join("curriculum/compatibility/legacy-weeks.yml").write(YAML.dump(mapping), encoding: "UTF-8")

      return assert_raises(Curriculum::LegacyWeekCompiler::ValidationError) do
        Curriculum::LegacyWeekCompiler.new(root: root).load_and_validate!
      end
    end
  end
end
