# frozen_string_literal: true

require "json"
require "pathname"
require "set"

require_relative "curriculum_json_schema"
require_relative "curriculum_strict_yaml"

module Curriculum
  # Compiles the historical Week 00-48 entry points from canonical outcome
  # slices. The compatibility route owns navigation only; chapter prose and
  # learner progress remain authoritative in catalog.yml and PROGRESS.md.
  class LegacyWeekCompiler
    MAPPING_PATH = "curriculum/compatibility/legacy-weeks.yml"
    SCHEMA_PATH = "schemas/legacy-week-slices.schema.json"
    CATALOG_PATH = "curriculum/catalog.yml"
    PROGRESS_PATH = "PROGRESS.md"
    MARKER = "<!-- generated by scripts/sync-legacy-learning-entry.rb; edit curriculum/compatibility/legacy-weeks.yml -->"
    SECTIONS = %w[required practice_diagnosis review support].freeze
    PRIMARY_SECTIONS = %w[required practice_diagnosis].freeze
    SECTION_ROLES = {
      "required" => "primary",
      "practice_diagnosis" => "primary",
      "review" => "refresh",
      "support" => "support"
    }.freeze
    OUTCOME_IDS = %w[explain build diagnose].freeze
    MASTERY_PROFILES = {
      "L1-L2" => %w[timed-teach-back guided-experiment boundary-diagnosis].freeze,
      "L2" => %w[timed-teach-back runnable-artifact boundary-test].freeze,
      "L2+" => %w[timed-teach-back runnable-artifact fault-diagnosis requirement-change].freeze,
      "L3" => %w[timed-teach-back independent-build fault-diagnosis requirement-change tradeoff-defense].freeze
    }.freeze

    class ValidationError < StandardError
      attr_reader :code, :path

      def initialize(code, message, path: MAPPING_PATH)
        @code = code
        @path = path
        super("[#{code}] #{path}: #{message}")
      end
    end

    attr_reader :root, :mapping, :catalog, :chapters, :outcomes, :primary_owner

    def initialize(root:)
      @root = Pathname(root).expand_path
    end

    def load_and_validate!
      @mapping = load_yaml(MAPPING_PATH)
      @catalog = load_yaml(CATALOG_PATH)
      schema = load_json(SCHEMA_PATH)
      schema_errors = JsonSchema.new(schema).validate(mapping)
      unless schema_errors.empty?
        error = schema_errors.first
        fail!("E_WEEK_SCHEMA", "#{error.pointer} #{error.message}")
      end

      @chapters = catalog.fetch("chapters").to_h { |chapter| [chapter.fetch("id"), chapter] }
      @outcomes = chapters.each_with_object({}) do |(chapter_id, chapter), result|
        chapter.fetch("outcomes").each do |outcome|
          result["#{chapter_id}##{outcome.fetch('id')}"] = [chapter, outcome]
        end
      end
      validate_contract!
      self
    rescue KeyError => error
      fail!("E_WEEK_INPUT", "missing required field #{error.message}")
    rescue ArgumentError => error
      fail!("E_WEEK_SCHEMA", error.message, path: SCHEMA_PATH)
    end

    def expected_outputs
      ensure_loaded!
      result = { root.join("weeks/README.md") => weeks_index }
      mapping.fetch("weeks").each do |week|
        number = format("%02d", week.fetch("week"))
        result[root.join("weeks/week-#{number}.md")] = week_page(week)
        if week.fetch("week") <= 8
          result[root.join("learning-kits/week-#{number}/concepts.md")] = kit_concepts_page(week)
        end
      end
      result
    end

    def check!
      drift = expected_outputs.select { |path, content| !path.file? || path.read(encoding: "UTF-8") != content }
      return if drift.empty?

      fail!("E_WEEK_ADAPTER_DRIFT", drift.keys.map { |path| path.relative_path_from(root) }.join(", "))
    end

    def write!
      expected_outputs.each do |path, content|
        path.dirname.mkpath
        temporary = path.sub_ext("#{path.extname}.tmp-#{Process.pid}")
        temporary.binwrite(content)
        temporary.rename(path)
      ensure
        temporary.delete if temporary && temporary.exist?
      end
    end

    def coverage_summary
      ensure_loaded!
      primary = mapping.fetch("weeks").flat_map do |week|
        PRIMARY_SECTIONS.flat_map { |section| week.fetch(section) }
      end
      {
        "weeks" => mapping.fetch("weeks").length,
        "chapters" => primary.map { |ref| ref.split("#", 2).first }.uniq.length,
        "catalog_chapters" => chapters.length,
        "primary_outcomes" => primary.length,
        "catalog_outcomes" => outcomes.length
      }
    end

    private

    def load_yaml(relative)
      path = root.join(relative)
      reject_unsafe_input!(path, relative)
      StrictYaml.load_file(path.to_s, display_path: relative)
    end

    def load_json(relative)
      path = root.join(relative)
      reject_unsafe_input!(path, relative)
      StrictJson.load(path.binread.force_encoding(Encoding::UTF_8))
    rescue JSON::ParserError, StrictJson::DuplicateKeyError => error
      fail!("E_WEEK_SCHEMA", error.message, path: relative)
    end

    def reject_unsafe_input!(path, relative)
      fail!("E_WEEK_INPUT", "required input is missing", path: relative) unless path.file?
      fail!("E_WEEK_INPUT", "symbolic-link inputs are forbidden", path: relative) if path.symlink?
    end

    def validate_contract!
      fail!("E_WEEK_POLICY", "section_roles must equal #{SECTION_ROLES.inspect}") unless mapping.fetch("section_roles") == SECTION_ROLES
      validate_budget_policy!
      validate_mastery_policy!
      validate_weeks!
      validate_primary_coverage!
      validate_non_primary_order!
    end

    def validate_budget_policy!
      policy = mapping.fetch("budget_policy")
      fail!("E_WEEK_BUDGET", "Week 00 policy must be exactly 8-12 hours") unless policy.fetch("week_00") == { "minimum" => 8, "maximum" => 12 }
      fail!("E_WEEK_BUDGET", "standard week policy must be exactly 15-18 hours") unless policy.fetch("standard_weeks") == { "minimum" => 15, "maximum" => 18 }
      fail!("E_WEEK_BUDGET", "section_keys must preserve the four canonical sections") unless policy.fetch("section_keys") == SECTIONS
    end

    def validate_mastery_policy!
      policy = mapping.fetch("mastery_policy")
      fail!("E_MASTERY_POLICY", "mastery evidence profiles do not match the route contract") unless policy.fetch("profiles") == MASTERY_PROFILES

      assignments = policy.fetch("required_assignments")
      expected = {
        "machine_learning" => { "weeks" => [39], "required_mastery" => "L1-L2" },
        "artificial_intelligence" => { "weeks" => [40, 41, 42, 43], "required_mastery" => "L2+" }
      }
      fail!("E_MASTERY_POLICY", "ML/AI required mastery assignments must equal #{expected.inspect}") unless assignments == expected
    end

    def validate_weeks!
      weeks = mapping.fetch("weeks")
      fail!("E_WEEK_SET", "week numbers must be exactly 0..48") unless weeks.map { |week| week.fetch("week") } == (0..48).to_a
      themes = progress_themes

      weeks.each do |week|
        number = week.fetch("week")
        expected_theme = themes.fetch(number)
        unless week.fetch("progress_theme") == expected_theme
          fail!("E_PROGRESS_THEME", "Week #{format('%02d', number)} must preserve PROGRESS theme #{expected_theme.inspect}")
        end

        validate_week_budget!(week)
        mastery = week.fetch("required_mastery")
        expected_evidence = mapping.fetch("mastery_policy").fetch("profiles").fetch(mastery)
        unless week.fetch("evidence_requirements") == expected_evidence
          fail!("E_MASTERY_EVIDENCE", "Week #{format('%02d', number)} evidence must exactly match #{mastery}")
        end

        refs = SECTIONS.flat_map { |section| week.fetch(section) }
        duplicate = duplicate_values(refs)
        fail!("E_WEEK_DUPLICATE_REF", "Week #{format('%02d', number)} repeats #{duplicate.join(', ')}") unless duplicate.empty?
        refs.each { |ref| fail!("E_OUTCOME_REF", "unknown outcome reference #{ref}") unless outcomes.key?(ref) }
        week.fetch("required").each do |ref|
          fail!("E_OUTCOME_SECTION", "#{ref} must use required only for explain") unless ref.end_with?("#explain")
        end
        week.fetch("practice_diagnosis").each do |ref|
          fail!("E_OUTCOME_SECTION", "#{ref} must use practice_diagnosis only for build/diagnose") unless ref.end_with?("#build") || ref.end_with?("#diagnose")
        end
        if PRIMARY_SECTIONS.all? { |section| week.fetch(section).empty? }
          fail!("E_PRIMARY_COVERAGE", "Week #{format('%02d', number)} has no primary outcome")
        end
      end

      assignment_policy = mapping.fetch("mastery_policy").fetch("required_assignments")
      assignment_policy.each_value do |assignment|
        assignment.fetch("weeks").each do |number|
          actual = weeks.fetch(number).fetch("required_mastery")
          expected = assignment.fetch("required_mastery")
          fail!("E_MASTERY_ASSIGNMENT", "Week #{format('%02d', number)} must require #{expected}, got #{actual}") unless actual == expected
        end
      end
    end

    def validate_week_budget!(week)
      number = week.fetch("week")
      budget = week.fetch("budget_hours")
      policy = mapping.fetch("budget_policy").fetch(number.zero? ? "week_00" : "standard_weeks")
      unless budget.fetch("minimum") == policy.fetch("minimum") && budget.fetch("maximum") == policy.fetch("maximum")
        fail!("E_WEEK_BUDGET", "Week #{format('%02d', number)} must declare #{policy['minimum']}-#{policy['maximum']} hours")
      end
      target = budget.fetch("target")
      unless target.between?(budget.fetch("minimum"), budget.fetch("maximum"))
        fail!("E_WEEK_BUDGET", "Week #{format('%02d', number)} target must be inside its range")
      end
      allocation = budget.fetch("allocation")
      unless allocation.keys == SECTIONS && allocation.values.inject(0, :+) == target
        fail!("E_WEEK_BUDGET", "Week #{format('%02d', number)} allocation must use canonical order and sum to target")
      end
      SECTIONS.each do |section|
        has_refs = !week.fetch(section).empty?
        has_hours = allocation.fetch(section).positive?
        unless has_refs == has_hours
          fail!("E_WEEK_BUDGET", "Week #{format('%02d', number)} #{section} refs and allocated hours must both be present or absent")
        end
      end
    end

    def validate_primary_coverage!
      primary = mapping.fetch("weeks").flat_map do |week|
        PRIMARY_SECTIONS.flat_map { |section| week.fetch(section) }
      end
      duplicates = duplicate_values(primary)
      expected = outcomes.keys.to_set
      actual = primary.to_set
      missing = (expected - actual).to_a.sort
      extra = (actual - expected).to_a.sort
      unless duplicates.empty? && missing.empty? && extra.empty?
        fail!(
          "E_PRIMARY_COVERAGE",
          "expected #{expected.length} unique primary outcomes; actual=#{primary.length} " \
          "duplicates=#{duplicates.join(',')} missing=#{missing.join(',')} extra=#{extra.join(',')}"
        )
      end
      @primary_owner = {}
      mapping.fetch("weeks").each do |week|
        PRIMARY_SECTIONS.each do |section|
          week.fetch(section).each { |ref| primary_owner[ref] = week.fetch("week") }
        end
      end
    end

    def validate_non_primary_order!
      mapping.fetch("weeks").each do |week|
        number = week.fetch("week")
        week.fetch("review").each do |ref|
          owner = primary_owner.fetch(ref)
          fail!("E_REFRESH_ORDER", "#{ref} cannot refresh before its primary week #{owner}") unless owner < number
        end
        week.fetch("support").each do |ref|
          owner = primary_owner.fetch(ref)
          fail!("E_SUPPORT_ORDER", "#{ref} cannot support before its primary week #{owner}") unless owner < number
        end
      end
    end

    def progress_themes
      themes = {}
      root.join(PROGRESS_PATH).each_line do |line|
        match = line.match(/^\|\s*(\d{2})\s*\|\s*([^|]+?)\s*\|/)
        themes[match[1].to_i] = match[2].strip if match
      end
      fail!("E_PROGRESS_THEME", "PROGRESS.md must contain Week 00-48 themes", path: PROGRESS_PATH) unless themes.keys.sort == (0..48).to_a
      themes
    end

    def weeks_index
      rows = mapping.fetch("weeks").map do |week|
        number = format("%02d", week.fetch("week"))
        budget = week.fetch("budget_hours")
        "- [Week #{number}：#{week.fetch('title')}](./week-#{number}.md) — #{budget.fetch('minimum')}—#{budget.fetch('maximum')} 小时，必达 #{week.fetch('required_mastery')}"
      end.join("\n")

      <<~MARKDOWN
        #{MARKER}
        # Week 00—48 兼容索引

        > 默认课程入口已经迁移到 [2026.2 编程百科全书](../book/README.md)。本目录保留 `PROGRESS.md` 的 Week 00—48 主题，并用 outcome slice 组织必修、实践诊断、复习和支撑；不复制教材正文。

        百科章节的 `level` 是参考深度，路线页的“必达”是本次学习所需掌握深度。二者分开记录：机器学习必达 L1-L2，AI 应用必达 L2+，并不删除百科中的 L3 参考内容。

        ## 周次适配入口

        #{rows}

        ## 迁移与回滚

        - 映射源：[`curriculum/compatibility/legacy-weeks.yml`](../curriculum/compatibility/legacy-weeks.yml)。
        - 映射契约：[`curriculum/compatibility/README.md`](../curriculum/compatibility/README.md)。
        - 旧长页冻结标签：`#{mapping.fetch('rollback_tag')}`。
        - 学习证据仍只写入 [`PROGRESS.md`](../PROGRESS.md)，本索引生成不会修改它。
      MARKDOWN
    end

    def week_page(week)
      number = format("%02d", week.fetch("week"))
      budget = week.fetch("budget_hours")
      allocation = budget.fetch("allocation")
      kit = if week.fetch("week") <= 8
              <<~KIT
                - [保留的实践、考核与追问包](../learning-kits/week-#{number}/README.md)
                - [本周无 AI 考核](../learning-kits/week-#{number}/assessment.md)
              KIT
            else
              "- [阶段考核总表](../ASSESSMENTS.md)\n"
            end

      <<~MARKDOWN
        #{MARKER}
        # Week #{number} 兼容入口：#{week.fetch('title')}

        > 保留的进度主题：#{week.fetch('progress_theme')}。本页只安排权威章节中的 outcome slice，不复制教材正文，也不会改变真实学习状态、小时或分数。

        ## 本周投入与掌握边界

        - 预算：#{budget.fetch('minimum')}—#{budget.fetch('maximum')} 小时，目标 #{budget.fetch('target')} 小时。
        - 分配：必修 #{allocation.fetch('required')}h；实践与诊断 #{allocation.fetch('practice_diagnosis')}h；复习 #{allocation.fetch('review')}h；前置支撑 #{allocation.fetch('support')}h。
        - 路线必达：`#{week.fetch('required_mastery')}`；证据：#{week.fetch('evidence_requirements').map { |item| "`#{item}`" }.join('、')}。
        - 百科参考深度：#{reference_depth_summary(week)}。参考深度不自动提高本周必达等级。

        ## 必修解释（primary）

        #{outcome_rows(week.fetch('required'), "primary", root.join('weeks'))}

        ## 实践与诊断（primary）

        #{outcome_rows(week.fetch('practice_diagnosis'), "primary", root.join('weeks'))}

        ## 间隔复习（refresh）

        #{outcome_rows(week.fetch('review'), "refresh", root.join('weeks'))}

        ## 前置支撑（support）

        #{outcome_rows(week.fetch('support'), "support", root.join('weeks'))}

        `primary` outcome 只在全路线出现一次；`refresh` 和 `support` 只是复习或回看，不产生新的掌握声明。多个 outcome 可以由同一个综合实验共同取证，预算不按条目机械相乘。

        ## 周实践与考核

        #{kit.rstrip}
        - [全书阶段门](../curriculum/gates.yml)
        - [真实学习进度](../PROGRESS.md)

        ## 兼容边界

        - 章节目录、outcome 和前置关系以 [`curriculum/catalog.yml`](../curriculum/catalog.yml) 为准。
        - 本页是日历周兼容层，不是第二份教程；学习时打开链接后的章节正文。
        - 旧版恢复：从 `#{mapping.fetch('rollback_tag')}` 读取原页面，不要与当前 edition 混合编辑。
      MARKDOWN
    end

    def kit_concepts_page(week)
      number = format("%02d", week.fetch("week"))
      <<~MARKDOWN
        #{MARKER}
        # Week #{number} 权威概念入口

        > 本页按稳定 outcome ref 路由到百科正文。`primary` 是本周首次负责的 outcome；`refresh` 和 `support` 不能替代本周验收。

        ## 必修解释（primary）

        #{outcome_rows(week.fetch('required'), "primary", root.join('learning-kits', "week-#{number}"))}

        ## 实践与诊断（primary）

        #{outcome_rows(week.fetch('practice_diagnosis'), "primary", root.join('learning-kits', "week-#{number}"))}

        ## 间隔复习（refresh）

        #{outcome_rows(week.fetch('review'), "refresh", root.join('learning-kits', "week-#{number}"))}

        ## 前置支撑（support）

        #{outcome_rows(week.fetch('support'), "support", root.join('learning-kits', "week-#{number}"))}

        先打开链接完成章节“学习前检查”，再按本周 section 取证。旧讲义可从标签 `#{mapping.fetch('rollback_tag')}` 查阅，但不得与当前章节混合更新。
      MARKDOWN
    end

    def outcome_rows(refs, role, from_directory)
      return "- 无。" if refs.empty?

      refs.map do |ref|
        chapter, outcome = outcomes.fetch(ref)
        target = root.join(chapter.fetch("path"))
        relative = target.relative_path_from(from_directory).to_s
        "- [#{chapter.fetch('title')}](#{relative}) — `#{ref}` · `#{role}` · #{outcome.fetch('text')}"
      end.join("\n")
    end

    def reference_depth_summary(week)
      refs = PRIMARY_SECTIONS.flat_map { |section| week.fetch(section) }
      depths = refs.map { |ref| outcomes.fetch(ref).first.fetch("level") }.uniq
      depths.sort_by { |level| %w[L1 L1-L2 L2 L2+ L3].index(level) || 99 }.map { |level| "`#{level}`" }.join("、")
    end

    def duplicate_values(values)
      counts = Hash.new(0)
      values.each { |value| counts[value] += 1 }
      counts.select { |_value, count| count > 1 }.keys.sort
    end

    def ensure_loaded!
      fail!("E_WEEK_INPUT", "compiler must load and validate inputs first") unless mapping && catalog
    end

    def fail!(code, message, path: MAPPING_PATH)
      raise ValidationError.new(code, message, path: path)
    end
  end
end
