#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"
require "yaml"

ROOT = Pathname(__dir__).join("..").expand_path
MAPPING_PATH = ROOT.join("curriculum/compatibility/legacy-weeks.yml")
CATALOG_PATH = ROOT.join("curriculum/catalog.yml")
MARKER = "<!-- generated by scripts/sync-legacy-learning-entry.rb; edit curriculum/compatibility/legacy-weeks.yml -->"

def load_yaml(path)
  YAML.safe_load(path.read, permitted_classes: [], permitted_symbols: [], aliases: false)
rescue Psych::Exception => error
  abort "invalid YAML #{path.relative_path_from(ROOT)}: #{error.message}"
end

def validate_mapping!(mapping, chapters)
  abort "legacy mapping must be an object" unless mapping.is_a?(Hash)
  abort "unsupported legacy mapping schema" unless mapping["schema_version"] == 1
  abort "legacy mapping policy must be thin-adapter" unless mapping["policy"] == "thin-adapter"

  weeks = mapping["weeks"]
  abort "legacy mapping must contain 49 weeks" unless weeks.is_a?(Array) && weeks.length == 49
  numbers = weeks.map { |week| week["week"] }
  abort "legacy week numbers must be exactly 0..48" unless numbers == (0..48).to_a

  weeks.each do |week|
    abort "week #{week.inspect} has invalid title" unless week["title"].is_a?(String) && !week["title"].strip.empty?
    ids = week["chapter_ids"]
    abort "week #{week['week']} must map at least one chapter" unless ids.is_a?(Array) && !ids.empty?
    abort "week #{week['week']} repeats chapter IDs" unless ids.uniq == ids
    missing = ids.reject { |id| chapters.key?(id) }
    abort "week #{week['week']} references unknown chapters: #{missing.join(', ')}" unless missing.empty?
  end
end

def chapter_rows(ids, chapters, from_directory)
  ids.map do |id|
    chapter = chapters.fetch(id)
    target = ROOT.join(chapter.fetch("path"))
    relative = target.relative_path_from(from_directory).to_s
    "- [#{chapter.fetch('title')}](#{relative}) (`#{id}`)"
  end.join("\n")
end

def week_page(week, chapters, mapping)
  number = format("%02d", week.fetch("week"))
  rows = chapter_rows(week.fetch("chapter_ids"), chapters, ROOT.join("weeks"))
  kit = if week.fetch("week") <= 8
          <<~KIT
            - [保留的实践、考核与追问包](../learning-kits/week-#{number}/README.md)
            - [本周无 AI 考核](../learning-kits/week-#{number}/assessment.md)
          KIT
        else
          "- [阶段考核总表](../ASSESSMENTS.md)\n"
        end

  <<~MARKDOWN
    #{MARKER}
    # Week #{number} 兼容入口：#{week.fetch('title')}

    > 本页保留 `PROGRESS.md` 的既有周次语义，但不再复制教材正文。权威内容来自 2026.2 百科章节；旧长页可从标签 `#{mapping.fetch('rollback_tag')}` 恢复。课程建设不会改变你的真实学习状态、小时或分数。

    ## 本周权威章节

    #{rows}

    阅读时按每章“学习前检查 → 正文 → 示例 → 实验 → 公开练习”执行。遇到缺失前置时沿章节中的可点击先修链接回补，不按日期强行推进。

    ## 实践与考核

    #{kit.rstrip}
    - [全书阶段门](../curriculum/gates.yml)
    - [真实学习进度](../PROGRESS.md)

    ## 兼容边界

    - 本页只是旧日历周到权威章节的适配层，不是第二份教程。
    - `weeks/` 不再维护独立概念清单；章节目录和前置关系以 `curriculum/catalog.yml` 为准。
    - 旧版恢复：从 `#{mapping.fetch('rollback_tag')}` 读取原页面；不要把旧正文与当前 edition 混合编辑。
  MARKDOWN
end

def weeks_index(weeks)
  rows = weeks.map do |week|
    number = format("%02d", week.fetch("week"))
    "- [Week #{number}：#{week.fetch('title')}](./week-#{number}.md)"
  end.join("\n")

  <<~MARKDOWN
    #{MARKER}
    # 旧 48 周计划兼容索引

    > 默认课程入口已经迁移到 [2026.2 编程百科全书](../book/README.md)。本目录只保留 `PROGRESS.md` 的 Week 00—48 周次语义，并把每周映射到唯一权威章节；不再维护重复教材正文。

    第一次系统学习优先使用[零基础路线](../curriculum/routes/zero-base.yml)；有真实诊断证据时可使用[48 模块加速路线](../curriculum/routes/accelerated-48.yml)。日历周和能力模块不是同一概念，是否推进取决于证据而不是日期。

    ## 周次适配入口

    #{rows}

    ## 迁移与回滚

    - 映射源：[`curriculum/compatibility/legacy-weeks.yml`](../curriculum/compatibility/legacy-weeks.yml)。
    - 旧长页冻结标签：`pre-encyclopedia-2026-07-16`。
    - 学习证据仍只写入 [`PROGRESS.md`](../PROGRESS.md)，本索引生成不会修改它。
  MARKDOWN
end

def kit_concepts_page(week, chapters, mapping)
  number = format("%02d", week.fetch("week"))
  rows = chapter_rows(week.fetch("chapter_ids"), chapters, ROOT.join("learning-kits", "week-#{number}"))
  <<~MARKDOWN
    #{MARKER}
    # Week #{number} 权威概念入口

    > 旧版 `concepts.md` 的重复讲义已停止维护。以下百科章节是当前唯一权威正文；实践、考核、答案和面试追问仍保留在本教学包。旧讲义可从标签 `#{mapping.fetch('rollback_tag')}` 查阅，但不得与当前章节混合更新。

    #{rows}

    先完成每章的“学习前检查”，再按章节顺序阅读。教师模式应加载这些章节的实际正文，而不是仅凭本页标题讲解。
  MARKDOWN
end

mapping = load_yaml(MAPPING_PATH)
catalog = load_yaml(CATALOG_PATH)
chapters = catalog.fetch("chapters").to_h { |chapter| [chapter.fetch("id"), chapter] }
validate_mapping!(mapping, chapters)

expected = { ROOT.join("weeks/README.md") => weeks_index(mapping.fetch("weeks")) }
mapping.fetch("weeks").each do |week|
  number = format("%02d", week.fetch("week"))
  expected[ROOT.join("weeks/week-#{number}.md")] = week_page(week, chapters, mapping)
  if week.fetch("week") <= 8
    expected[ROOT.join("learning-kits/week-#{number}/concepts.md")] = kit_concepts_page(week, chapters, mapping)
  end
end

mode = ARGV.first
abort "usage: ruby scripts/sync-legacy-learning-entry.rb --write|--check" unless %w[--write --check].include?(mode)

drift = expected.select { |path, content| !path.file? || path.read(encoding: "UTF-8") != content }
if mode == "--check"
  unless drift.empty?
    warn "legacy learning entry drift:"
    drift.each_key { |path| warn "- #{path.relative_path_from(ROOT)}" }
    exit 1
  end
  puts "legacy learning entry OK: weeks=49 concept-adapters=9"
  exit 0
end

expected.each do |path, content|
  path.dirname.mkpath
  temporary = path.sub_ext("#{path.extname}.tmp-#{Process.pid}")
  temporary.binwrite(content)
  temporary.rename(path)
end
puts "legacy learning entry synchronized: weeks=49 concept-adapters=9"
